name: Run Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated version

    - name: Set up Python
      uses: actions/setup-python@v4  # Updated version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 lxml selenium webdriver-manager

    - name: Run your script
      run: |
        python ViolationSearch.py
